// lib/flourData.ts
import { Flour } from '@/types';

export const flours: Flour[] = [
  {
    id: 'zyto-pelny-przemial',
    name: 'Mąka żytnia pełny przemiał (Typ 2000)',
    type: 'rye',
    glutenFree: false,
    typNumber: 2000,
    hydrationAbsorption: 0.85,
    hydrationBoost: 0.15,
    glycemicIndex: 'low',
    protein: 10.5,
    fiber: 15.1,
    keyNutrients: ['kwasy fenolowe', 'lignany', 'błonnik rozpuszczalny', 'selen'],
    fermentationNotes:
      'Wymaga zakwaszenia. Kwas fitynowy neutralizowany przez min. 12h fermentacji zakwasowej.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Najwyższa zawartość błonnika wśród zbóż chlebowych. Niski IG dzięki strukturze skrobi opornej.',
  },
  {
    id: 'orkisz-650',
    name: 'Mąka orkiszowa Typ 650',
    type: 'spelt',
    glutenFree: false,
    typNumber: 650,
    hydrationAbsorption: 0.68,
    hydrationBoost: 0.05,
    glycemicIndex: 'medium',
    protein: 14.2,
    fiber: 4.3,
    keyNutrients: ['niacyna', 'ryboflawina', 'magnez', 'tryptofan'],
    fermentationNotes:
      'Gluten orkiszowy delikatniejszy – nie przefermentować. Optymalna autoliza 30 min.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Starożytna pszenica o lepszym profilu aminokwasowym niż pszenica zwyczajna. Więcej cynku i żelaza.',
  },
  {
    id: 'orkisz-00',
    name: 'Mąka orkiszowa Typ 00 (biała)',
    type: 'spelt',
    glutenFree: false,
    typNumber: 0,
    hydrationAbsorption: 0.58,
    hydrationBoost: 0.0,
    glycemicIndex: 'high',
    protein: 12.8,
    fiber: 1.2,
    keyNutrients: ['niacyna', 'tryptofan'],
    fermentationNotes: 'Krótka autoliza 20 min. Nie wyrabiać zbyt intensywnie.',
    organic: false,
    fodmapSafe: false,
    notes:
      'Biała mąka orkiszowa – lepsza strawność niż pszenna Typ 00, ale wciąż wysoki IG.',
  },
  {
    id: 'orkisz-2000',
    name: 'Mąka orkiszowa Typ 2000 (pełny przemiał)',
    type: 'spelt',
    glutenFree: false,
    typNumber: 2000,
    hydrationAbsorption: 0.82,
    hydrationBoost: 0.14,
    glycemicIndex: 'low',
    protein: 15.3,
    fiber: 11.8,
    keyNutrients: ['magnez', 'żelazo', 'cynk', 'błonnik', 'tryptofan'],
    fermentationNotes:
      'Wymaga dłuższej hydratacji wstępnej (1h). Najlepiej fermentacja zakwasowa 18-24h.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Pełny przemiał orkiszu – wszystkie składniki odżywcze ziarna. Doskonała do chleba rzemieślniczego.',
  },
  {
    id: 'samopsza-pelny',
    name: 'Mąka samopsza pełny przemiał',
    type: 'einkorn',
    glutenFree: false,
    typNumber: undefined,
    hydrationAbsorption: 0.72,
    hydrationBoost: 0.09,
    glycemicIndex: 'low',
    protein: 16.8,
    fiber: 9.2,
    keyNutrients: ['luteina', 'beta-karoten', 'witamina E', 'cynk'],
    fermentationNotes:
      'Najstarsza pszenica. Bardzo kruchy gluten – delikatne wyrabianie. Autoliza 45 min.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Genom AA – najprostszy gluten. Bogata w karotenoidy, nadaje ciastu złoty kolor.',
  },
  {
    id: 'plaskurka',
    name: 'Mąka płaskurka pełny przemiał',
    type: 'emmer',
    glutenFree: false,
    typNumber: undefined,
    hydrationAbsorption: 0.74,
    hydrationBoost: 0.10,
    glycemicIndex: 'low',
    protein: 14.9,
    fiber: 8.7,
    keyNutrients: ['kwas krzemowy', 'magnez', 'fosfor'],
    fermentationNotes:
      'Mocny smak orzechowy. Świetna w blendach 30-50% z mąką chlebową.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Starożytna pszenica tetraploidalna. Kwas krzemowy wspiera skórę i włosy.',
  },
  {
    id: 'cieciorka',
    name: 'Mąka z ciecierzycy',
    type: 'legume',
    glutenFree: true,
    typNumber: undefined,
    hydrationAbsorption: 0.78,
    hydrationBoost: 0.12,
    glycemicIndex: 'low',
    protein: 22.4,
    fiber: 10.8,
    keyNutrients: ['foliany', 'żelazo', 'cynk', 'błonnik prebiotyczny'],
    fermentationNotes:
      'Smak strączkowy łagodzi się przez fermentację 24h. Wymaga blendowania z mąkami GF.',
    organic: true,
    fodmapSafe: false,
    notes:
      'Najwyższa zawartość białka wśród mąk bezglutenowych. Kompletny profil aminokwasowy w połączeniu ze zbożami.',
  },
  {
    id: 'soczewica',
    name: 'Mąka z soczewicy',
    type: 'legume',
    glutenFree: true,
    typNumber: undefined,
    hydrationAbsorption: 0.76,
    hydrationBoost: 0.11,
    glycemicIndex: 'low',
    protein: 25.8,
    fiber: 10.3,
    keyNutrients: ['żelazo', 'foliany', 'potas'],
    fermentationNotes:
      'Szybko fermentuje – max 12h. Może nadać różowy odcień ciastu.',
    organic: true,
    fodmapSafe: false,
    notes:
      'Bardzo wysoka zawartość białka. Idealna do bezglutenowych proteinowych bułeczek.',
  },
  {
    id: 'ryzowa',
    name: 'Mąka ryżowa',
    type: 'gf-blend',
    glutenFree: true,
    typNumber: undefined,
    hydrationAbsorption: 0.62,
    hydrationBoost: 0.04,
    glycemicIndex: 'high',
    protein: 6.5,
    fiber: 2.4,
    keyNutrients: ['mangan', 'selen'],
    fermentationNotes:
      'Bardzo delikatna struktura. Wymaga dodatku gumy ksantanowej lub babki jajowatej.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Podstawa blendów GF. Neutralny smak, ale wysoki IG – najlepiej blendować z mąkami o niskim IG.',
  },
  {
    id: 'gryczana',
    name: 'Mąka gryczana',
    type: 'gf-blend',
    glutenFree: true,
    typNumber: undefined,
    hydrationAbsorption: 0.76,
    hydrationBoost: 0.11,
    glycemicIndex: 'low',
    protein: 13.3,
    fiber: 10.0,
    keyNutrients: ['rutyna', 'magnez', 'błonnik'],
    fermentationNotes:
      'Wyrazisty, ziemisty smak. Fermentacja 18h łagodzi goryczkę.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Bogata w rutynę – flawonoid wzmacniający naczynia krwionośne. Niski IG.',
  },
  {
    id: 'amarantus',
    name: 'Mąka amarantusowa',
    type: 'gf-blend',
    glutenFree: true,
    typNumber: undefined,
    hydrationAbsorption: 0.68,
    hydrationBoost: 0.07,
    glycemicIndex: 'low',
    protein: 14.5,
    fiber: 6.7,
    keyNutrients: ['skwalen', 'żelazo', 'wapń', 'lizyna'],
    fermentationNotes:
      'Lekko orzechowy smak. Nie przekraczać 30% w blendzie GF.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Pseudozboże o kompletnym białku. Zawiera skwalen – przeciwutleniacz.',
  },
  {
    id: 'kukurydziana',
    name: 'Mąka kukurydziana',
    type: 'gf-blend',
    glutenFree: true,
    typNumber: undefined,
    hydrationAbsorption: 0.55,
    hydrationBoost: 0.02,
    glycemicIndex: 'medium',
    protein: 8.1,
    fiber: 7.3,
    keyNutrients: ['zeaksantyna', 'luteina', 'błonnik'],
    fermentationNotes:
      'Klasyczna w Pinsa Romana. Daje chrupkość i złoty kolor.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Karotenoidy – zeaksantyna i luteina chronią wzrok. Średni IG.',
  },
  {
    id: 'jeczmienna',
    name: 'Mąka jęczmienna',
    type: 'other',
    glutenFree: false,
    typNumber: undefined,
    hydrationAbsorption: 0.70,
    hydrationBoost: 0.07,
    glycemicIndex: 'low',
    protein: 10.8,
    fiber: 15.6,
    keyNutrients: ['beta-glukany', 'chrom', 'błonnik rozpuszczalny'],
    fermentationNotes:
      'Beta-glukany nadają kremową teksturę. Doskonała w chlebie niskoglikemicznym.',
    organic: true,
    fodmapSafe: true,
    notes:
      'Najwyższa zawartość beta-glukanów – obniżają cholesterol i stabilizują glikemię.',
  },
  {
    id: 'owsiane-platki',
    name: 'Mąka z płatków owsianych (mielona)',
    type: 'other',
    glutenFree: false,
    typNumber: undefined,
    hydrationAbsorption: 0.80,
    hydrationBoost: 0.13,
    glycemicIndex: 'low',
    protein: 13.5,
    fiber: 10.1,
    keyNutrients: ['beta-glukany', 'awentramidy', 'magnez'],
    fermentationNotes:
      'Awentramidy – unikalne przeciwutleniacze owsa. Wymaga dłuższej hydratacji.',
    organic: true,
    fodmapSafe: false,
    notes:
      'Awentramidy działają przeciwzapalnie. Sprawdzić certyfikat GF przy celiakii.',
  },
];