export type DietaryTag = "dairy-free" | "low-fodmap" | "low-gi" | "gluten-free";

export interface Ingredient {
  name: string;
  amountPerPortion: number; // Ilość bazowa przypadająca na 1 jednostkę porcji
  unit: string;
}

export interface Recipe {
  id: string;
  slug: string;
  title: string;
  category: "pizza" | "focaccia" | "pieczywo";
  defaultPortions: number;
  portionUnitName: string;
  timeMinutes: string;
  shortDescription: string;
  recommendedFlourId?: string;
  tags: DietaryTag[];
  ingredients: Ingredient[];
  steps: string[];
}

export const DIETARY_TAG_LABELS: Record<DietaryTag, string> = {
  "dairy-free": "Bez Nabiału",
  "low-fodmap": "Low FODMAP",
  "low-gi": "Niski IG",
  "gluten-free": "Bezgluten",
};

export const RECIPES: Recipe[] = [
  {
    id: "pizza-romana-orkisz-72h",
    slug: "pizza-romana-orkiszowa-72h",
    title: "Pizza Romana Orkiszowa 00 (72h Fermentacji)",
    category: "pizza",
    defaultPortions: 2,
    portionUnitName: "pizze (kule ok. 405 g)",
    timeMinutes: "72h zimnej fermentacji",
    shortDescription: "Ultra-lekka pizza rzymska na Bio Mące Orkiszowej Typ 00. Maksymalna redukcja fruktanów i chrupiący brzeg.",
    recommendedFlourId: "niro-orkisz-00",
    tags: ["dairy-free", "low-fodmap"],
    ingredients: [
      { name: "Bio Mąka Orkiszowa Typ 00 (NIRO BIO)", amountPerPortion: 242.5, unit: "g" },
      { name: "Woda zimna (ok. 4°C)", amountPerPortion: 157.5, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 0.5, unit: "g" },
      { name: "Oliwa z oliwek extra virgin", amountPerPortion: 6, unit: "g" },
      { name: "Sól morska drobna", amountPerPortion: 6, unit: "g" },
      { name: "Sos ze słodkich pomidorów włoskich", amountPerPortion: 70, unit: "g" },
      { name: "Mortadella Bologna lub warzywa", amountPerPortion: 60, unit: "g" },
      { name: "Pistacje prażone (kruszone)", amountPerPortion: 15, unit: "g" },
    ],
    steps: [
      "Autoliza (45 min): Połącz mąkę orkiszową 00 z 90% wody (zimnej). Odstaw pod przykryciem.",
      "Wyrabianie (15 min): Rozpuść drożdże w reszcie wody, dodaj do ciasta, a następnie wmieszaj sól i oliwę do uzyskania gładkości.",
      "Fermentacja wstępna (2h): Pozostaw ciasto w temperaturze pokojowej, wykonując 2 serie stretch & fold co 40 minut.",
      "Cold Proofing (64h): Zamknij szczelnie w pojemniku i odstaw do lodówki (4°C).",
      "Kulkowanie (2h 15 min): Wyjmij, podziel na 2 kule i odłóż do lodówki na 2 godziny.",
      "Ocieplanie i rozciąganie (2h 45 min): Rozciągaj na naoliwionej blasze.",
      "Pieczenie dwuetapowe (250°C): Najpierw spód z sosem na dół pieca (7–9 min), potem dodanie obłożenia na 4–6 min.",
    ],
  },
  {
    id: "chleb-zytnio-orkiszowy-24h",
    slug: "chleb-zytnio-orkiszowy-z-ziarnami-24h",
    title: "Chleb Żytnio-Orkiszowy z Ziarnami (Drożdżowy 24h)",
    category: "pieczywo",
    defaultPortions: 1,
    portionUnitName: "bochenek (ok. 850 g)",
    timeMinutes: "24h (w tym 19h cold proofing)",
    shortDescription: "Gęsty, tradycyjny chleb bez zakwasu na mąkach z pełnego przemiału Typ 2000. Czysty skład i powolna praca enzymów.",
    recommendedFlourId: "niro-zytnia-2000",
    tags: ["dairy-free", "low-gi"],
    ingredients: [
      { name: "Bio Mąka Żytnia Typ 2000 (NIRO BIO)", amountPerPortion: 250, unit: "g" },
      { name: "Bio Mąka Orkiszowa Typ 2000 (NIRO BIO)", amountPerPortion: 200, unit: "g" },
      { name: "Woda chłodna, filtrowana", amountPerPortion: 330, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 1.5, unit: "g" },
      { name: "Sól morska drobnokrystaliczna", amountPerPortion: 10, unit: "g" },
      { name: "Siemię lniane (złote lub brązowe)", amountPerPortion: 15, unit: "g" },
      { name: "Pestki słonecznika", amountPerPortion: 15, unit: "g" },
      { name: "Kminek mielony (opcjonalnie)", amountPerPortion: 2, unit: "g" },
    ],
    steps: [
      "Autoliza (45 min): Wymieszaj mąki Typ 2000 z 300 ml wody do zwilżenia otrąb.",
      "Wyrabianie (10 min): Dodaj drożdże rozpuszczone w 30 ml wody, sól oraz ziarna. Wyrabiaj krótko (5–7 min) do jednolitości.",
      "Fermentacja wstępna: 2 godziny w temperaturze pokojowej (21–23°C).",
      "Formowanie: Uformuj bochenek i przełóż do koszyka rozrostowego obsypanego mąką żytnią.",
      "Cold Proofing (19h): Wstaw koszyk w szczelnej torbie do lodówki (4°C).",
      "Pieczenie w garnku żeliwnym: Wyjmij 1h przed piecem. Piecz 25 min pod przykryciem w 240°C, a następnie 20 min w 210°C bez pokrywki.",
      "Studzenie: Odparuj na kratce min. 3–4 godziny przed krojeniem.",
    ],
  },
  {
    id: "pizza-3-maki-samopsza-40h",
    slug: "pizza-pradawna-samopsza-orkisz-zyto-40h",
    title: "Pizza Pradawna z Samopszą (40h Fermentacji)",
    category: "pizza",
    defaultPortions: 2,
    portionUnitName: "pizze (lekkostrawne)",
    timeMinutes: "40h fermentacji chłodniczej",
    shortDescription: "Kompozycja pradawnych mąk (samopsza, orkisz, żyto 2000). Prosta struktura glutenu i niski indeks glikemiczny.",
    recommendedFlourId: "niro-pradawna-mieszanka",
    tags: ["dairy-free", "low-fodmap", "low-gi"],
    ingredients: [
      { name: "Bio Mąka z Samopszy / Mieszanka Pradawna", amountPerPortion: 175, unit: "g" },
      { name: "Woda zimna", amountPerPortion: 114, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 0.6, unit: "g" },
      { name: "Sól kamienna / morska", amountPerPortion: 4.5, unit: "g" },
      { name: "Oliwa z oliwek", amountPerPortion: 5, unit: "g" },
      { name: "Passata ze słodkich pomidorów (bez czosnku/cebuli)", amountPerPortion: 70, unit: "g" },
    ],
    steps: [
      "Wymieszaj mąki ze świeżego przemiału z wodą i odstaw na 30 minut.",
      "Dodaj drożdże, po 5 minutach sól i oliwę. Ze względu na delikatny gluten samopszy zagniataj bez gwałtownego rozrywania.",
      "Fermentuj 2h w temperaturze pokojowej ze składaniem co godzinę.",
      "Wstaw ciasto do chłodu (4°C) na 40 godzin – w tym czasie enzymy przeprowadzą wstępne trawienie fruktanów.",
      "Uformuj kule na 3h przed pieczeniem. Rozciągaj ostrożnie dłońmi na semolinie lub mące ryżowej.",
      "Piecz w 250°C na rozgrzanym kamieniu lub blasze przez 6–8 minut.",
    ],
  },
  {
    id: "buleczki-orkiszowe-mozzarella",
    slug: "buleczki-orkiszowe-z-mozzarella-i-czosnkiem",
    title: "Bułeczki Orkiszowe z Mozzarellą i Masłem Czosnkowym",
    category: "pieczywo",
    defaultPortions: 14,
    portionUnitName: "bułeczek (po ok. 60 g)",
    timeMinutes: "70h (w tym 64h w lodówce)",
    shortDescription: "Długo dojrzewające ciasto orkiszowe 00 kryjące ciągnącą mozzarellę, glazurowane masłem czosnkowym.",
    recommendedFlourId: "niro-orkisz-00",
    tags: [],
    ingredients: [
      { name: "Bio Mąka Orkiszowa Typ 00 (NIRO BIO)", amountPerPortion: 34.6, unit: "g" },
      { name: "Woda zimna (ok. 4°C)", amountPerPortion: 22.5, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 0.07, unit: "g" },
      { name: "Oliwa z oliwek extra virgin", amountPerPortion: 0.85, unit: "g" },
      { name: "Sól morska", amountPerPortion: 0.85, unit: "g" },
      { name: "Mozzarella w bloku (kostka)", amountPerPortion: 20, unit: "g" },
      { name: "Masło czosnkowe z parmezanem i natką", amountPerPortion: 12, unit: "g" },
      { name: "Ziarna sezamu (do posypania)", amountPerPortion: 1.5, unit: "g" },
    ],
    steps: [
      "Autoliza mąki orkiszowej 00 z 290 ml wody przez 45 minut.",
      "Wyrabianie z drożdżami (1 g na całość), solą i oliwą. Fermentacja wstępna 2h z 2 seriami stretch & fold.",
      "Cold Proofing w 4°C przez 64 godziny.",
      "Podziel zimne ciasto na 14 równych porcji (ok. 60 g), w środek każdej zawiń 20 g mozzarelli i zroluj w kulkę.",
      "Ułóż w naoliwionej formie i pozostaw do rozrostu na 2h 45 min, aż połączą się bokami.",
      "Posmaruj obficie masłem czosnkowym, posyp sezamem i piecz w 250°C przez 12–15 minut.",
    ],
  },
  {
    id: "focaccia-pszenna-39h",
    slug: "focaccia-pszenna-na-grill-39h",
    title: "Focaccia Pszenna Długo Fermentowana (39h)",
    category: "focaccia",
    defaultPortions: 6,
    portionUnitName: "dużych porcji (blacha 30x25)",
    timeMinutes: "39h (w tym 24h lodówka)",
    shortDescription: "Niezwykle puszysta focaccia z hydratacją 75%. Złocista skórka z solą gruboziarnistą i oliwą z oliwek.",
    recommendedFlourId: "niro-orkisz-00",
    tags: ["dairy-free", "low-fodmap"],
    ingredients: [
      { name: "Mąka pszenna / orkiszowa Typ 00", amountPerPortion: 83.3, unit: "g" },
      { name: "Woda letnia", amountPerPortion: 62.5, unit: "ml" },
      { name: "Sól", amountPerPortion: 1.5, unit: "g" },
      { name: "Drożdże instant (suche)", amountPerPortion: 0.65, unit: "g" },
      { name: "Oliwa z oliwek (do ciasta i formy)", amountPerPortion: 12, unit: "ml" },
      { name: "Sól gruboziarnista i rozmaryn", amountPerPortion: 2, unit: "g" },
    ],
    steps: [
      "Wymieszaj składniki łyżką tylko do zniknięcia suchych pasm mąki (5 min).",
      "Otocz kulę ciasta w 2 łyżkach oliwy i wstaw do lodówki na 24 godziny (dozwolone do 36h).",
      "Przełóż ciasto na naoliwioną blachę 30x25 cm i rozciągnij palcami.",
      "Drugie wyrastanie w cieple przez 2–3 godziny do wyraźnej puszystości.",
      "Zrób wgłębienia palcami, zalej oliwą, posyp solą gruboziarnistą oraz ziołami.",
      "Piecz w 250°C przez 16–20 minut na złocisto-chrupiący kolor.",
    ],
  },
  {
    id: "pinsa-orkiszowo-zytnia",
    slug: "pinsa-orkiszowo-zytnia-dwuetapowa",
    title: "Pinsa Orkiszowo-Żytnia (Wypiek Dwuetapowy)",
    category: "pizza",
    defaultPortions: 2,
    portionUnitName: "owalne pinsy",
    timeMinutes: "18h fermentacji (2h To + 14h Tk + 2h To)",
    shortDescription: "Chrupiący rzymski spód z mąk pełnoziarnistych Typ 2000. Dwuetapowy wypiek gwarantujący lekkość.",
    recommendedFlourId: "niro-orkisz-2000",
    tags: ["dairy-free", "low-gi"],
    ingredients: [
      { name: "Bio Mąka Orkiszowa Typ 2000 (NIRO BIO)", amountPerPortion: 110, unit: "g" },
      { name: "Bio Mąka Żytnia Typ 2000 (NIRO BIO)", amountPerPortion: 65, unit: "g" },
      { name: "Woda chłodna (hydratacja ok. 68%)", amountPerPortion: 120, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 1, unit: "g" },
      { name: "Sól morska", amountPerPortion: 3.8, unit: "g" },
      { name: "Oliwa z oliwek", amountPerPortion: 6, unit: "g" },
    ],
    steps: [
      "Wymieszaj mąki z wodą i drożdżami, po chwili dodaj sól oraz oliwę.",
      "Fermentacja: 2h w temperaturze pokojowej, 14h w chłodzie lodówki i 2h ocieplenia.",
      "Uformuj charakterystyczny podłużny, owalny kształt, delikatnie ugniatając opuszkami palców.",
      "Etap 1 pieczenia: Sam spód z oliwą w 250°C przez 4–6 minut do ścięcia struktury.",
      "Etap 2 pieczenia: Nałożenie dodatków i dopieczenie przez 3–5 minut.",
    ],
  },
  {
    id: "detroit-orkiszowo-zytnie",
    slug: "detroit-orkiszowo-zytnie-z-pieczarkami",
    title: "Pizza Detroit Orkiszowo-Żytnia na Blasze",
    category: "pizza",
    defaultPortions: 4,
    portionUnitName: "porcje z blachy",
    timeMinutes: "1h 15 min (lub 16h zimna)",
    shortDescription: "Karmelizowane brzegi serowe, puszyste ciasto orkiszowo-żytnie i charakterystyczne pasy sosu pomidorowego.",
    recommendedFlourId: "niro-orkisz-700",
    tags: [],
    ingredients: [
      { name: "Bio Mąka Orkiszowa Typ 700 / jasna", amountPerPortion: 50, unit: "g" },
      { name: "Bio Mąka Żytnia Typ 2000", amountPerPortion: 25, unit: "g" },
      { name: "Woda ciepła (35–40°C)", amountPerPortion: 62.5, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 2.5, unit: "g" },
      { name: "Sól", amountPerPortion: 1.2, unit: "g" },
      { name: "Oliwa z oliwek do formy", amountPerPortion: 4, unit: "ml" },
      { name: "Mozzarella w bloku (tarta)", amountPerPortion: 45, unit: "g" },
      { name: "Podsmażone pieczarki i sos pomidorowy", amountPerPortion: 50, unit: "g" },
    ],
    steps: [
      "Zrób zaczyn drożdżowy z letnią wodą. Połącz z mąkami, solą i oliwą, wyrabiając 8–10 minut.",
      "Wyrastanie: 45–60 min w cieple lub noc w lodówce dla głębszego aromatu.",
      "Wyłóż ciastem prostokątną formę wysmarowaną oliwą, dociskając do krawędzi.",
      "Ułóż tartą mozzarellę aż po same ranty blachy (da to chrupiącą karmelizację serową) i dodaj pieczarki.",
      "Na wierzch wylej podłużne pasy gęstego sosu ze słodkich włoskich pomidorów.",
      "Piecz w 240–250°C przez 15–18 minut do mocnego zrumienienia boków.",
    ],
  },
  {
    id: "orkiszowe-tapas-salami",
    slug: "orkiszowe-tapas-salami-przekaska",
    title: "Orkiszowe Tapas Salami do Wina",
    category: "pizza",
    defaultPortions: 15,
    portionUnitName: "krążków tapas",
    timeMinutes: "14h fermentacji w lodówce",
    shortDescription: "Małe, chrupiące placki z mąki orkiszowej Typ 650 z pikantnym salami, mozzarellą i oliwkami.",
    recommendedFlourId: "niro-orkisz-650",
    tags: [],
    ingredients: [
      { name: "Bio Mąka Orkiszowa Typ 650 (NIRO BIO)", amountPerPortion: 26.6, unit: "g" },
      { name: "Woda chłodna", amountPerPortion: 15.6, unit: "ml" },
      { name: "Świeże drożdże", amountPerPortion: 0.13, unit: "g" },
      { name: "Sól", amountPerPortion: 0.6, unit: "g" },
      { name: "Oliwa z oliwek", amountPerPortion: 1, unit: "g" },
      { name: "Gęsta passata pomidorowa", amountPerPortion: 8, unit: "g" },
      { name: "Mozzarella wiórki", amountPerPortion: 10, unit: "g" },
      { name: "Plasterek pikantnego salami & oliwki", amountPerPortion: 8, unit: "g" },
    ],
    steps: [
      "Autoliza: Wymieszaj mąkę orkiszową 650 z wodą i drożdżami na 15 minut.",
      "Dodaj sól oraz oliwę, wyrabiaj 3–4 minuty. Odstaw do lodówki na 12–18 godzin.",
      "Podziel na małe kuleczki (ok. 40–45 g) i odstaw do wyrośnięcia na blasze na 60 minut.",
      "Rozgnieć kuleczki palcami od środka na małe dyski z rantem.",
      "Nałóż łyżeczkę sosu, mozzarellę, plaster salami i krążki oliwek.",
      "Piecz w 250°C przez 13–15 minut. Po wyjęciu posyp suszoną bazylią.",
    ],
  },
  {
    id: "pizzerinka-air-fryer-espanola",
    slug: "pizzerinka-espanola-z-air-fryera",
    title: "Pizzerinka Española z Air Fryera (Dwuetapowa)",
    category: "pizza",
    defaultPortions: 1,
    portionUnitName: "pizzerinka (kosz 20x20 cm)",
    timeMinutes: "72h fermentacji (lub szybka)",
    shortDescription: "Chrupiący spód w 12 minut bez odpalania dużego pieca. Ciasto orkiszowe 00, chorizo i rzemieślniczy ser.",
    recommendedFlourId: "niro-orkisz-00",
    tags: [],
    ingredients: [
      { name: "Bio Mąka Orkiszowa Typ 00 (NIRO BIO)", amountPerPortion: 100, unit: "g" },
      { name: "Woda (hydratacja 65%)", amountPerPortion: 65, unit: "ml" },
      { name: "Sól i drożdże (zgodnie z bazą 72h)", amountPerPortion: 3, unit: "g" },
      { name: "Oliwa z oliwek", amountPerPortion: 2.5, unit: "g" },
      { name: "Sosy pomidorowe (czerwony i żółty)", amountPerPortion: 40, unit: "g" },
      { name: "Plasterki chorizo wysokiej jakości", amountPerPortion: 30, unit: "g" },
      { name: "Ser kraftowy krótkodojrzewający & bazylia", amountPerPortion: 25, unit: "g" },
    ],
    steps: [
      "Rozciągnij kawałek dojrzałego ciasta na papierze do pieczenia na wymiar kosza 20x20 cm.",
      "Etap 1 (7 min w 200°C w Air Fryerze): Piecz wyłącznie z nałożonym sosem, by ciasto urosło i ścięło strukturę.",
      "Etap 2 (5 min w 200°C): Wysuń kosz, ułóż plasterki chorizo i dopiekaj 5 minut, aż wytopi się aromat.",
      "Po wyjęciu: Na gorący spód wyłóż kawałki sera kraftowego i listki bazylii (ser zmięknie naturalnie bez przypalenia).",
    ],
  },
];